Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
config = configparser.ConfigParser()
config.sections()

config.read('betfair.ini')

username = config['betfair']['username']
pw = config['betfair']['pw']
app_key = config['betfair']['app_key']

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
[0;32m<ipython-input-3-c35214fe65ab>[0m in [0;36m<module>[0;34m[0m
[1;32m      4[0m [0mconfig[0m[0;34m.[0m[0mread[0m[0;34m([0m[0;34m'betfair.ini'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;34m[0m[0m
[0;32m----> 6[0;31m [0musername[0m [0;34m=[0m [0mconfig[0m[0;34m[[0m[0;34m'betfair'[0m[0;34m][0m[0;34m[[0m[0;34m'username'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      7[0m [0mpw[0m [0;34m=[0m [0mconfig[0m[0;34m[[0m[0;34m'betfair'[0m[0;34m][0m[0;34m[[0m[0;34m'pw'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m      8[0m [0mapp_key[0m [0;34m=[0m [0mconfig[0m[0;34m[[0m[0;34m'betfair'[0m[0;34m][0m[0;34m[[0m[0;34m'app_key'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/anaconda3/lib/python3.8/configparser.py[0m in [0;36m__getitem__[0;34m(self, key)[0m
[1;32m    958[0m     [0;32mdef[0m [0m__getitem__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mkey[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    959[0m         [0;32mif[0m [0mkey[0m [0;34m!=[0m [0mself[0m[0;34m.[0m[0mdefault_section[0m [0;32mand[0m [0;32mnot[0m [0mself[0m[0;34m.[0m[0mhas_section[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 960[0;31m             [0;32mraise[0m [0mKeyError[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    961[0m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_proxies[0m[0;34m[[0m[0mkey[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m    962[0m [0;34m[0m[0m

[0;31mKeyError[0m: 'betfair'
KeyError: 'betfair'

